# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 244d4d4266dbfb1bd5e8cfdbd52b41cc2a8aee6f2e6bfce6009fc73d2a37f36cd0387bdb0ff0dad3e1b9e1a80003f072cdcad16d875dd28f2c7b16d0a6290e34

test:
  secret_key_base: e045a31ca88fbe979323f131fa33ac1d9b16193dfc5db03f7a208242f3d649d6f5c9b008e3285ad1187153f41aeda69cc8aeeab6bbfe21e5ffba30366849a04b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
